apiVersion: v1
kind: Service
metadata:
  name: altova-ip
  namespace: prod
  labels:
    app: altova-ip 
spec:
  type: LoadBalancer
  selector:
    app: altova-api
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 88
    
    - port: 600
      protocol: TCP
      targetPort: 80